name: Sprint Release Notes

on:
  workflow_dispatch:
    inputs:
      sprint_name:
        description: 'Sprint name (e.g., Sprint5)'
        required: true

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests notion-client jira
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug directory
        run: |
          pwd
          ls -la

      - name: Generate release notes
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        run: |
          python generate_release_notes.py ${{ github.event.inputs.sprint_name }}

      - name: Convert JSON to Markdown
        run: |
          echo "# Release Notes for ${{ github.event.inputs.sprint_name }}" > release_notes.md
          echo "" >> release_notes.md
          echo "## What's Changed" >> release_notes.md
          if [ -f release_notes.json ]; then
            jq -r '.tickets[] | "- \(.type) - \(.key): \(.summary) (Assignee: \(.assignee))"' release_notes.json >> release_notes.md
          else
            echo "No tickets found for this sprint." >> release_notes.md
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.sprint_name }}
          release_name: Release ${{ github.event.inputs.sprint_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
